server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:./db/testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
app:
  jwtExpirationInMs: 86400000
logging:
  level:
    org.springframework: INFO
    org.meena.treeforum.hierarchical_forum.controller: INFO